exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: primery

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/leapofazzam123/Primery"
  
title: Primery
description: An imporved version of Primer Jekyll theme
